### ISSUE TITLE
Вылет программы при неопределенных обстоятельствах.

### ISSUE THREAD

**Issue by daniilsavenya** [Viruzober/MagicKeys#1]
Здравствуйте!
Мне удалось таки отловить ту самую ошибку, при которой как раз и происходил вылет. Как оказалось, насколько я смог понять, дело в каком-то странном исключении и, скорее всего, оно как-то связано именно с Контактом.
Ниже приведу код обоих ошибок.

`Application: MagicKeys.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MagicKeys.MagicKeys.InvokeFromString(String InvokeFunc)
   at MagicKeys.MagicKeys.PluginDetector()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

Вторая ошибка, следующая сразу же за первой.

`Faulting application name: MagicKeys.exe, version: 1.0.0.0, time stamp: 0x5ec598f1
Faulting module name: KERNELBASE.dll, version: 10.0.19041.292, time stamp: 0x84cd251b
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x304c
Faulting application start time: 0x01d653d61db97026
Faulting application path: D:\Repositories\MagicKeys\Dist\x64\MagicKeys.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e91c5be4-798f-4ccb-b72d-71f23262b5fe
Faulting package full name: 
Faulting package-relative application ID: `

Что это может быть и как сие исправляется?

**Comment by a11cf0** [comment]
Исправлено полностью.
